version: '3.8'

services:
  webapi:
    container_name: myapp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - webapi-network
    restart: always

networks:
  webapi-network:
    driver: bridge
