@WebAPI_HostAddress = http://localhost:5153

###
# для книги
# создание книги
POST {{WebAPI_HostAddress}}/User/Book
Content-Type: application/json

{
    "idUser": "1",
    "NameBook": "Моя новая книга"
}
###
# получение всех книг + проверка токена (если что, то его поменять надо)
# формально, запускается первым делом, после входа, и без него никуда дальше не уйти 
GET {{WebAPI_HostAddress}}/User/Book/all
Content-Type: application/json

"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjEwNTgyMDgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.4-So8RWEEWiMiN-6Uss9DDZzONHVnOlbM3wi9C90j6c"

###
GET {{WebAPI_HostAddress}}/User/Book/1
Accept: application/json

###
# изменение книги (1 - id книги)
PUT {{WebAPI_HostAddress}}/User/Book/3
Content-Type: application/json

{
    "NameBook": "Измененное название книги"
}

###
# удаление книги
DELETE {{WebAPI_HostAddress}}/User/Book/3