@WebAPI_HostAddress = http://localhost:5153

###
# для персонажа и блоков
# создание персонажа и блоков
POST {{WebAPI_HostAddress}}/User/Book/Character
Content-Type: application/json

{
    "IdBook": 1

}
###
GET {{WebAPI_HostAddress}}/User/Book/Character/all
Content-Type: application/json

"1"
###
GET {{WebAPI_HostAddress}}/User/Book/Character/4
Accept: application/json

###
# изменение персонажа и блоков
PUT {{WebAPI_HostAddress}}/User/Book/Character/5
Content-Type: application/json

{
    "Name": "Обновленное имя персонажа",
    "Answer1Personality": "Обновленный ответ 1",
    "Answer2Personality": "Обновленный ответ 2",
    "Answer3Personality": "Обновленный ответ 3",
    "Answer4Personality": "Обновленный ответ 4",
    "Answer5Personality": "Обновленный ответ 5",
    "Answer6Personality": "Обновленный ответ 6",
    "Answer1Appearance": "Обновленный ответ 1",
    "Answer2Appearance": "Обновленный ответ 2",
    "Answer3Appearance": "Обновленный ответ 3",
    "Answer4Appearance": "Обновленный ответ 4",
    "Answer5Appearance": "Обновленный ответ 5",
    "Answer6Appearance": "Обновленный ответ 6",
    "Answer7Appearance": "Обновленный ответ 7",
    "Answer8Appearance": "Обновленный ответ 8",
    "Answer9Appearance": "Обновленный ответ 9",
    "Answer1Temperament": "Обновленный ответ 1",
    "Answer2Temperament": "Обновленный ответ 2",
    "Answer3Temperament": "Обновленный ответ 3",
    "Answer4Temperament": "Обновленный ответ 4",
    "Answer5Temperament": "Обновленный ответ 5",
    "Answer6Temperament": "Обновленный ответ 6",
    "Answer7Temperament": "Обновленный ответ 7",
    "Answer8Temperament": "Обновленный ответ 8",
    "Answer9Temperament": "Обновленный ответ 9",
    "Answer10Temperament": "Обновленный ответ 10",
    "Answer1ByHistory": "Обновленный ответ 1",
    "Answer2ByHistory": "Обновленный ответ 2",
    "Answer3ByHistory": "Обновленный ответ 3",
    "Answer4ByHistory": "Обновленный ответ 4",
    "Answer5ByHistory": "Обновленный ответ 5"
}
###
# удаление персонажа, блоков и добавленных атрибутов
DELETE {{WebAPI_HostAddress}}/User/Book/Character/5

###
# для атрибутов
# создание атрибута
POST {{WebAPI_HostAddress}}/User/Book/Character/3/addedattribute
Content-Type: application/json

{
    "NumberAnswer": "1",
    "NameAttribute": "Новое имя"
}
###
# изменение атрибута
PUT {{WebAPI_HostAddress}}/User/Book/Character/4/addedattribute/1
Content-Type: application/json

"Содержимое"
###
# удаление атрибута
DELETE {{WebAPI_HostAddress}}/User/Book/Character/3/addedattribute/2
