@WebAPI_HostAddress = http://localhost:5153

###
# для персонажа и блоков
# создание персонажа и блоков
POST {{WebAPI_HostAddress}}/User/Book/Character
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

{
    "BookId": 1

}
###
GET {{WebAPI_HostAddress}}/User/Book/Character/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

"1"
###
GET {{WebAPI_HostAddress}}/User/Book/Character/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

###
GET {{WebAPI_HostAddress}}/User/Book/Character
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

###
# изменение персонажа и блоков
PUT {{WebAPI_HostAddress}}/User/Book/Character/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

{
    "Name": "Обновленное имя персонажа",
    "Answers": [
        "Обновленный ответ 1",
        "Обновленный ответ 2",
        "Обновленный ответ 3",
        "Обновленный ответ 4",
        "Обновленный ответ 5",
        "Обновленный ответ 6",
        "Обновленный ответ 1",
        "Обновленный ответ 2",
        "Обновленный ответ 3",
        "Обновленный ответ 4",
        "Обновленный ответ 5",
        "Обновленный ответ 6",
        "Обновленный ответ 7",
        "Обновленный ответ 8",
        "Обновленный ответ 9",
        "Обновленный ответ 1",
        "Обновленный ответ 2",
        "Обновленный ответ 3",
        "Обновленный ответ 4",
        "Обновленный ответ 5",
        "Обновленный ответ 6",
        "Обновленный ответ 7",
        "Обновленный ответ 8",
        "Обновленный ответ 9",
        "Обновленный ответ 1",
        "Обновленный ответ 2",
        "Обновленный ответ 3",
        "Обновленный ответ 4",
        "Обновленный ответ 5"
    ]
}
###
# удаление персонажа, блоков и добавленных атрибутов
DELETE {{WebAPI_HostAddress}}/User/Book/Character/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

###
# для атрибутов
# создание атрибута
POST {{WebAPI_HostAddress}}/User/Book/Character/1/addedattribute
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

{
    "NumberAnswer": "1",
    "NameAttribute": "Новое имя"
}
###
# изменение атрибута
PUT {{WebAPI_HostAddress}}/User/Book/Character/1/addedattribute/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

"Содержимое"
###
# удаление атрибута
DELETE {{WebAPI_HostAddress}}/User/Book/Character/1/addedattribute/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4
