@WebAPI_HostAddress = http://localhost:5153

###
# для связи
# создание связи
POST {{WebAPI_HostAddress}}/User/Book/Scheme/Connection
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ5MzczNTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.o3ASrC2LA94RJUr8oOoy0J_sLhAQNoVfEz1TzNWsDts

{
    "BookId": "1",
    "Character1Id": "1",
    "Character2Id": "2",
    "TypeConnection": "Сиблинг"
}

###
GET {{WebAPI_HostAddress}}/User/Book/Scheme/Connection/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ5MzczNTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.o3ASrC2LA94RJUr8oOoy0J_sLhAQNoVfEz1TzNWsDts

"1"

###
GET {{WebAPI_HostAddress}}/User/Book/Scheme/Connection/4
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ5MzczNTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.o3ASrC2LA94RJUr8oOoy0J_sLhAQNoVfEz1TzNWsDts
