@WebAPI_HostAddress = http://localhost:5153

###
# для связи
# создание связи
POST {{WebAPI_HostAddress}}/User/Book/Scheme/Connection
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjUwOTg0ODEsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.Omg1Y9rXTb0GLQrsqsWVQrbppfVDw2WPlqy3nTFRC0I

{
    "BookId": "1",
    "Character1Id": "1",
    "Character2Id": "2",
    "TypeConnection": "Сиблинг"
}

###
GET {{WebAPI_HostAddress}}/User/Book/Scheme/Connection/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjUwOTg0ODEsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.Omg1Y9rXTb0GLQrsqsWVQrbppfVDw2WPlqy3nTFRC0I

"1"

###
GET {{WebAPI_HostAddress}}/User/Book/Scheme/Connection/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjUwOTg0ODEsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.Omg1Y9rXTb0GLQrsqsWVQrbppfVDw2WPlqy3nTFRC0I
