@WebAPI_HostAddress = http://localhost:5153

###
# для галереи
# добавление изображения в галерею 
POST {{WebAPI_HostAddress}}/User/Book/Character/Gallery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

{
    "CharacterId": "1",
    "PictureId": "1"
}
###
GET {{WebAPI_HostAddress}}/User/Book/Character/Gallery/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4

"1"
###
# удаление галереии
DELETE {{WebAPI_HostAddress}}/User/Book/Character/Gallery/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3NDQxMTkyNzgsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.mpm4OsDa01WFyXQL4H8nx1ug7w5y3-xKcFcjcu0JuS4
