@WebAPI_HostAddress = http://localhost:5153

###
# для галереи
# добавление изображения в галерею 
POST {{WebAPI_HostAddress}}/User/Book/Character/Gallery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWU0IiwiZXhwIjoxNzI0MjM0MzExLCJpc3MiOiJ5b3VyX2lzc3VlciIsImF1ZCI6InlvdXJfYXVkaWVuY2UifQ.i033gN6BLn_YYofe5EQxPVYi30H_KzfUvPSVtyWdVDA

{
    "IdCharacter": "1",
    "IdPicture": "1"
}
###
GET {{WebAPI_HostAddress}}/User/Book/Character/Gallery/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWU0IiwiZXhwIjoxNzI0MjM0MzExLCJpc3MiOiJ5b3VyX2lzc3VlciIsImF1ZCI6InlvdXJfYXVkaWVuY2UifQ.i033gN6BLn_YYofe5EQxPVYi30H_KzfUvPSVtyWdVDA

"1"
###
# удаление галереии
DELETE {{WebAPI_HostAddress}}/User/Book/Character/Gallery/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWU0IiwiZXhwIjoxNzI0MjM0MzExLCJpc3MiOiJ5b3VyX2lzc3VlciIsImF1ZCI6InlvdXJfYXVkaWVuY2UifQ.i033gN6BLn_YYofe5EQxPVYi30H_KzfUvPSVtyWdVDA
