@WebAPI_HostAddress = http://localhost:5153

###
# для галереи
# добавление изображения в галерею 
POST {{WebAPI_HostAddress}}/User/Book/Character/Gallery
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjUwOTg0ODEsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.Omg1Y9rXTb0GLQrsqsWVQrbppfVDw2WPlqy3nTFRC0I

{
    "CharacterId": "1",
    "PictureId": "1"
}
###
GET {{WebAPI_HostAddress}}/User/Book/Character/Gallery/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjUwOTg0ODEsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.Omg1Y9rXTb0GLQrsqsWVQrbppfVDw2WPlqy3nTFRC0I

"1"
###
# удаление галереии
DELETE {{WebAPI_HostAddress}}/User/Book/Character/Gallery/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjUwOTg0ODEsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.Omg1Y9rXTb0GLQrsqsWVQrbppfVDw2WPlqy3nTFRC0I
