@WebAPI_HostAddress = http://localhost:5153

###
# для схемы
# создание схемы (подсхемы получается)
POST {{WebAPI_HostAddress}}/User/Book/Scheme
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ2NzA1MDAsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.wqhmvsv8CwTLwMrwiF3cnmv7lzxdS0RYmOEB2stU1jY

{
    "BookId": "1",
    "NameScheme": "Новое имя"
}
###
GET {{WebAPI_HostAddress}}/User/Book/Scheme/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ2NzA1MDAsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.wqhmvsv8CwTLwMrwiF3cnmv7lzxdS0RYmOEB2stU1jY

"1"
###
# изменение связи
PUT {{WebAPI_HostAddress}}/User/Book/Scheme/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ2NzA1MDAsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.wqhmvsv8CwTLwMrwiF3cnmv7lzxdS0RYmOEB2stU1jY

"2"
###
# удаление схемы
DELETE {{WebAPI_HostAddress}}/User/Book/Scheme/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjQ2NzA1MDAsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.wqhmvsv8CwTLwMrwiF3cnmv7lzxdS0RYmOEB2stU1jY
