@WebAPI_HostAddress = http://localhost:5153

###
# для таймлайна
# создание подтаймлайна
POST {{WebAPI_HostAddress}}/User/Book/Timeline
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MzY5NjExMTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.OePsPEsyz7BudPO_uvgsHqixx3v2X86Qc-7Re3Fihe0

{
    "BookId": "1",
    "NameTimeline": "Новое имя"
}
###
GET {{WebAPI_HostAddress}}/User/Book/Timeline/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MzY5NjExMTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.OePsPEsyz7BudPO_uvgsHqixx3v2X86Qc-7Re3Fihe0

"1"
###
# добавление события в таймлайн
PUT {{WebAPI_HostAddress}}/User/Book/Timeline/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MzY5NjExMTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.OePsPEsyz7BudPO_uvgsHqixx3v2X86Qc-7Re3Fihe0

"1"
###
# удаление таймлайна
DELETE {{WebAPI_HostAddress}}/User/Book/Timeline/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MzY5NjExMTUsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.OePsPEsyz7BudPO_uvgsHqixx3v2X86Qc-7Re3Fihe0
