@WebAPI_HostAddress = http://localhost:5153

###
# для таймлайна
# создание подтаймлайна
POST {{WebAPI_HostAddress}}/User/Book/Timeline
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjE0ODYyMjYsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.4GtpgfJ-treAn3yojL3zOWUAm7TNNt2Nvxb_-J-8H4o

{
    "IdBook": "1",
    "NameTimeline": "Новое имя"
}
###
GET {{WebAPI_HostAddress}}/User/Book/Timeline/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjE0ODYyMjYsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.4GtpgfJ-treAn3yojL3zOWUAm7TNNt2Nvxb_-J-8H4o

"1"
###
# добавление события в таймлайн
PUT {{WebAPI_HostAddress}}/User/Book/Timeline/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjE0ODYyMjYsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.4GtpgfJ-treAn3yojL3zOWUAm7TNNt2Nvxb_-J-8H4o

"2"
###
# удаление таймлайна
DELETE {{WebAPI_HostAddress}}/User/Book/Timeline/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlcm5hbWUiLCJleHAiOjE3MjE0ODYyMjYsImlzcyI6InlvdXJfaXNzdWVyIiwiYXVkIjoieW91cl9hdWRpZW5jZSJ9.4GtpgfJ-treAn3yojL3zOWUAm7TNNt2Nvxb_-J-8H4o
